#!/usr/bin/env python
"""main.py - auto-generated by softnanotools"""
from softnanotools.logger import Logger
logger = Logger('hydrogels')

import argparse

from .generate import main as generate
from .run import main as run

COMMANDS = {
    'run': run,
    'generate': generate,
    '_': lambda: print('Welcome to Hydrogels!')
}

def execute(command: str, **kwargs):
    return COMMANDS[command](**kwargs)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('command', nargs='?', default='_')
    execute(**vars(parser.parse_args()))
    return

if __name__ == '__main__':
    import doctest
    doctest.testmod()
