#!/usr/bin/env python
"""main.py - auto-generated by softnanotools"""
from softnanotools.logger import Logger
logger = Logger('hydrogels')
from typing import List
import argparse

from .generate import main as generate
from .run import main as run
from .setter import main as setter

COMMANDS = {
    'run': lambda **kwargs: logger.error(
        'hydrogels run has not been implemented, use hydrogels.run instead!'
    ),
    'generate': lambda **kwargs: logger.error(
        'hydrogels generate has not been implemented, '
        'use hydrogels.generate instead!'
    ),
    '_': lambda **kwargs: print('Welcome to Hydrogels!'),
    'set': setter
}

def execute(command: str, args: List[str]):
    return COMMANDS[command](*args)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('command', nargs='?', default='_')
    parser.add_argument('args', nargs='*')
    execute(**vars(parser.parse_args()))
    return

if __name__ == '__main__':
    import doctest
    doctest.testmod()
