#!/usr/bin/env python
"""run.py - auto-generated by softnanotools"""
from softnanotools.logger import Logger
logger = Logger("hydrogels.run")

def main():
    print('Welcome to the hydrogels simulation runner!')
    return

if __name__ == '__main__':
    import doctest
    doctest.testmod()
