#!/usr/bin/env python
"""run.py - auto-generated by softnanotools"""
from softnanotools.logger import Logger
logger = Logger("hydrogels.run")

import argparse

def execute(settings: str, lammps: bool = False, readdy: bool = False):
    return

def main(**kwargs):
    print('Welcome to the hydrogels simulation runner!')
    parser = argparse.ArgumentParser()
    parser.add_argument('settings')
    parser.add_argument('--lammps', action='store_true')
    parser.add_argument('--readdy', action='store_true')
    execute(**vars(parser.parse_args()))
    return

if __name__ == '__main__':
    import doctest
    doctest.testmod()
