#!/usr/bin/env python
"""_spatial.py - auto-generated by softnanotools"""
from softnanotools.logger import Logger
logger = Logger(__name__)

if __name__ == '__main__':
    import doctest
    doctest.testmod()
