#!/usr/bin/env python
"""diatomic.py - auto-generated by softnanotools"""
from softnanotools.logger import Logger
logger = Logger('DIATOMIC')

def main(**kwargs):
    logger.info('Running diatomic...')
    # insert code here
    logger.info('Done!')
    return

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='diatomic.py - auto-generated by softnanotools')
    main(**vars(parser.parse_args()))

