#!/usr/bin/env python
"""Convert a ReaDDy trajectory to LAMMPS data configuration files"""
from pathlib import Path
from softnanotools.logger import Logger
logger = Logger('MAIN')

from hydrogels.trajectory import ParticleTrajectory, TopologyTrajectory

READDY_TRAJ = Path('readdy.h5')
LAMMPS_TRAJ = Path('lammps') / 'lammps'

def main(**kwargs):
    logger.info('Running main...')

    # create LAMMPS trajectory directory
    LAMMPS_TRAJ.parent.mkdir(exist_ok=True)

    # import readdy trajectory
    pt = ParticleTrajectory(READDY_TRAJ)
    tt = TopologyTrajectory(READDY_TRAJ)

    # output
    tt.to_LAMMPS_configuration(
        LAMMPS_TRAJ,
        pt,
        comment="Generated from readdy-to-lammps"
    )

    logger.info('Done!')
    return

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='main.py - auto-generated by softnanotools')
    main(**vars(parser.parse_args()))
