#!/usr/bin/env python
"""plot_all.py - auto-generated by softnanotools"""
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from softnanotools.logger import Logger
logger = Logger('PLOT ALL')

plt.style.use('tableau-colorblind10')

SCHEMA = {
    'A': ['enzymes', [10, 20, 30, 40, 50]],
    'B': ['spring_length', [0.25, 0.50, 1.00, 1.50, 2.00]],
    'C': ['reaction_rate', [0.01, 0.1, 1.0, 10.0]],
    'D': ['diffusion_constant', [0.01, 0.1, 1.0, 10.0]]
}

def plot_ID(ID: str):
    fig, ax = plt.subplots()
    parameter, values = SCHEMA[ID]
    for i, value in enumerate(values):
        data = pd.read_csv(f'{ID}{i+1}.csv')
        params = dict(
            markevery=len(data) // 30 if len(data) > 50 else 5,
            errorevery=len(data) // 30 if len(data) > 50 else 5,
            capsize=2
        )
        ax.errorbar(
            data['t'],
            data['A_mean'],
            yerr=data['A_std'],
            fmt='x-',
            label=f'{value:.2f}',
            **params
        )

    ax.set_title(parameter.replace('_', ' '))
    ax.set_xlabel('Timestep', fontsize='xx-large')
    ax.set_ylabel('N', fontsize='xx-large')
    ax.legend(frameon=False, fontsize='x-large')

    fig.tight_layout()
    fig.savefig(f'{ID}.png')
    return

def main(**kwargs):
    logger.info('Running plot_all...')
    for ID in SCHEMA.keys():
        plot_ID(ID)
    logger.info('Done!')
    return

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(
        description='plot_all.py - auto-generated by softnanotools'
    )
    main(**vars(parser.parse_args()))
