#!/usr/bin/env python
"""_readdy.py - auto-generated by softnanotools"""
from softnanotools.logger import Logger
logger = Logger(__name__)

from .core import HydrogelsRunner

class ReaDDyRunner(HydrogelsRunner):
    def __init__(self):
        super().__init__()

if __name__ == '__main__':
    import doctest
    doctest.testmod()
