#!/usr/bin/env python
"""core.py - auto-generated by softnanotools"""
import yaml

from softnanotools.logger import Logger
logger = Logger(__name__)

from softnanotools.runner import Runner

class HydrogelsRunner(Runner):
    def __init__(self, settings: str):
        super().__init__()
        self.settings = settings
        with open(self.settings, 'r') as f:
            self.params = yaml.safe_load(f)

if __name__ == '__main__':
    import doctest
    doctest.testmod()
